apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-replica-set
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app-deep

      # same as pod yml
  template:
    metadata:
      labels:
        app: my-app-deep
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80